POST http://127.0.0.1:3000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "namaToko": "Toko Buku",
    "username": "tokobuku",
    # "username": "tttt",
    "email": "admin@tokobuku.com",
    "password": "password",
    "alamat": "Jl. Jend. Sudirman No. 1"
}

### Login
POST http://127.0.0.1:3000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@tokobuku.com",
    "password": "password"
}

### Get All Category

GET http://127.0.0.1:3000/api/v1/categories HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6IjRlNTU4NWI2LTczNWMtNDMyNS05Mjk1LTU5YTAyY2Y4YjkzZiIsImlkIjoiNjQ2Y2YwYjYtMGQ1My00ZDA4LTk3MzctMTlhNjBkNTlkMzZlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDA0NjM4OTAsImV4cCI6MTcwMDU1MDI5MH0.ecN53aOmajmUMb7dylOSO77ds1TPIQCzJELIRvV3EH0


### Create Category
POST http://127.0.0.1:3000/api/v1/categories HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6IjRlNTU4NWI2LTczNWMtNDMyNS05Mjk1LTU5YTAyY2Y4YjkzZiIsImlkIjoiNjQ2Y2YwYjYtMGQ1My00ZDA4LTk3MzctMTlhNjBkNTlkMzZlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDA0NjM4OTAsImV4cCI6MTcwMDU1MDI5MH0.ecN53aOmajmUMb7dylOSO77ds1TPIQCzJELIRvV3EH0

{
    "name": "Tas"
}

### Update Category
PUT http://127.0.0.1:3000/api/v1/categories/06dd53d0-43bb-4813-a0cf-88d854a93b55 HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6IjRlNTU4NWI2LTczNWMtNDMyNS05Mjk1LTU5YTAyY2Y4YjkzZiIsImlkIjoiNjQ2Y2YwYjYtMGQ1My00ZDA4LTk3MzctMTlhNjBkNTlkMzZlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDA0NjM4OTAsImV4cCI6MTcwMDU1MDI5MH0.ecN53aOmajmUMb7dylOSO77ds1TPIQCzJELIRvV3EH0

{
    "name": "Buku"
}

### Delete Category
DELETE http://127.0.0.1:3000/api/v1/categories/06dd53d0-43bb-4813-a0cf-88d854a93b55 HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6IjRlNTU4NWI2LTczNWMtNDMyNS05Mjk1LTU5YTAyY2Y4YjkzZiIsImlkIjoiNjQ2Y2YwYjYtMGQ1My00ZDA4LTk3MzctMTlhNjBkNTlkMzZlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDA0NjM4OTAsImV4cCI6MTcwMDU1MDI5MH0.ecN53aOmajmUMb7dylOSO77ds1TPIQCzJELIRvV3EH0

### Get All Product
GET http://127.0.0.1:3000/api/v1/products?categoryId=ffa16da9-d729-47de-a788-bc3107475077 HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6IjRlNTU4NWI2LTczNWMtNDMyNS05Mjk1LTU5YTAyY2Y4YjkzZiIsImlkIjoiNjQ2Y2YwYjYtMGQ1My00ZDA4LTk3MzctMTlhNjBkNTlkMzZlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDA0NjM4OTAsImV4cCI6MTcwMDU1MDI5MH0.ecN53aOmajmUMb7dylOSO77ds1TPIQCzJELIRvV3EH0

### Create Product
POST http://127.0.0.1:3000/api/v1/products HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6IjRlNTU4NWI2LTczNWMtNDMyNS05Mjk1LTU5YTAyY2Y4YjkzZiIsImlkIjoiNjQ2Y2YwYjYtMGQ1My00ZDA4LTk3MzctMTlhNjBkNTlkMzZlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDA0NjM4OTAsImV4cCI6MTcwMDU1MDI5MH0.ecN53aOmajmUMb7dylOSO77ds1TPIQCzJELIRvV3EH0

{
    "name": "Buku2",
    "hargaBeli": 10000,
    "hargaJual": 15000,
    "stock": 10,
    "categoryId": "ffa16da9-d729-47de-a788-bc3107475077"
}


### Get Product By Id
GET http://127.0.0.1:3000/api/v1/products/8259e3d4-2ec1-494d-b195-37b92f178df3 HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6IjRlNTU4NWI2LTczNWMtNDMyNS05Mjk1LTU5YTAyY2Y4YjkzZiIsImlkIjoiNjQ2Y2YwYjYtMGQ1My00ZDA4LTk3MzctMTlhNjBkNTlkMzZlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDA0NjM4OTAsImV4cCI6MTcwMDU1MDI5MH0.ecN53aOmajmUMb7dylOSO77ds1TPIQCzJELIRvV3EH0

### Get All Supplier
GET http://127.0.0.1:3000/api/v1/supliers HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6ImMxZmM3YzYzLTFkYzYtNDQ5Yy04ZWIyLTg4ZGMzNWU5MzA3OCIsImlkIjoiMTdlZWZhZWUtNmZjOC00NDM2LWExYzMtMzYwYTQxMzk3MjBlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDE0MzQ0MTEsImV4cCI6MTcwNDAyNjQxMX0.5zuRoYMqwnHWa7PQLq2F5eJav9l76NeI11u6czfP408

### Get All Customer
GET http://127.0.0.1:3000/api/v1/customers HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6ImMxZmM3YzYzLTFkYzYtNDQ5Yy04ZWIyLTg4ZGMzNWU5MzA3OCIsImlkIjoiMTdlZWZhZWUtNmZjOC00NDM2LWExYzMtMzYwYTQxMzk3MjBlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDE0MzQ0MTEsImV4cCI6MTcwNDAyNjQxMX0.5zuRoYMqwnHWa7PQLq2F5eJav9l76NeI11u6czfP408

### Payment Membership
POST http://127.0.0.1:3000/api/v1/membership/payment HTTP/1.1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWRhbmdJZCI6ImMxZmM3YzYzLTFkYzYtNDQ5Yy04ZWIyLTg4ZGMzNWU5MzA3OCIsImlkIjoiMTdlZWZhZWUtNmZjOC00NDM2LWExYzMtMzYwYTQxMzk3MjBlIiwibmFtYVRva28iOiJUb2tvIEJ1a3UiLCJ1c2VybmFtZSI6InRva29idWt1IiwiZW1haWwiOiJhZG1pbkB0b2tvYnVrdS5jb20iLCJhbGFtYXQiOiJKbC4gSmVuZC4gU3VkaXJtYW4gTm8uIDEiLCJpYXQiOjE3MDE0MzQ0MTEsImV4cCI6MTcwNDAyNjQxMX0.5zuRoYMqwnHWa7PQLq2F5eJav9l76NeI11u6czfP408